package com.todayplay.app.localization

data class HistoryStrings(
    val title: String,
    val subtitle: String,
    val sectionTitle: String,
    val sectionEnglish: String,
    val emptyTitle: String,
    val emptyBody: String,
    val startFirst: String,
    val relationshipLabel: String,
    val routeLabel: String,
    val stopCheckInLabel: String,
    val pointsLabel: String,
    val durationLabel: String,
    val completionLabel: String,
    val hiddenTaskLabel: String,
    val keywordsLabel: String,
    val openHint: String,
    val openAction: String,
    val replayAction: String,
)

fun historyStrings(locale: TodayPlayLocale): HistoryStrings = when (locale) {
    TodayPlayLocale.SimplifiedChinese -> HistoryStrings(
        title = "历史副本",
        subtitle = "library",
        sectionTitle = "已经玩过的今天",
        sectionEnglish = "played scripts",
        emptyTitle = "还没有通关记录",
        emptyBody = "先开一局今天，之后这里会替你收好那些普通但发光的片段。",
        startFirst = "去开第一局",
        relationshipLabel = "关系",
        routeLabel = "路线",
        stopCheckInLabel = "地点打卡",
        pointsLabel = "积分",
        durationLabel = "时长",
        completionLabel = "完成",
        hiddenTaskLabel = "隐藏任务",
        keywordsLabel = "关键词",
        openHint = "点开重温这场副本",
        openAction = "打开",
        replayAction = "再开类似一局",
    )
    TodayPlayLocale.TraditionalChinese -> HistoryStrings(
        title = "歷史副本",
        subtitle = "library",
        sectionTitle = "已經玩過的今天",
        sectionEnglish = "played scripts",
        emptyTitle = "還沒有通關紀錄",
        emptyBody = "先開一局今天，之後這裡會替你收好那些普通但發光的片段。",
        startFirst = "去開第一局",
        relationshipLabel = "關係",
        routeLabel = "路線",
        stopCheckInLabel = "地點打卡",
        pointsLabel = "積分",
        durationLabel = "時長",
        completionLabel = "完成",
        hiddenTaskLabel = "隱藏任務",
        keywordsLabel = "關鍵詞",
        openHint = "點開重溫這場副本",
        openAction = "打開",
        replayAction = "再開類似一局",
    )
    TodayPlayLocale.English -> HistoryStrings(
        title = "History",
        subtitle = "library",
        sectionTitle = "Days already played",
        sectionEnglish = "played scripts",
        emptyTitle = "No completed records yet",
        emptyBody = "Start one route quest first. Later, this page will keep the ordinary moments that turned bright.",
        startFirst = "Start the first route",
        relationshipLabel = "Relationship",
        routeLabel = "Route",
        stopCheckInLabel = "Stop check-ins",
        pointsLabel = "Points",
        durationLabel = "Duration",
        completionLabel = "Completed",
        hiddenTaskLabel = "Hidden task",
        keywordsLabel = "Keywords",
        openHint = "Open to replay this quest",
        openAction = "Open",
        replayAction = "Replay style",
    )
    TodayPlayLocale.Japanese -> HistoryStrings(
        title = "履歴",
        subtitle = "library",
        sectionTitle = "もう遊んだ今日",
        sectionEnglish = "played scripts",
        emptyTitle = "まだクリア記録はありません",
        emptyBody = "まず今日のルートを始めましょう。ここに、普通だけど少し光った時間が残ります。",
        startFirst = "最初のルートを始める",
        relationshipLabel = "関係",
        routeLabel = "ルート",
        stopCheckInLabel = "スポット到着",
        pointsLabel = "ポイント",
        durationLabel = "時間",
        completionLabel = "完了",
        hiddenTaskLabel = "隠しタスク",
        keywordsLabel = "キーワード",
        openHint = "開いてこのクエストを振り返る",
        openAction = "開く",
        replayAction = "似たルート",
    )
    TodayPlayLocale.Korean -> HistoryStrings(
        title = "히스토리",
        subtitle = "library",
        sectionTitle = "이미 플레이한 오늘",
        sectionEnglish = "played scripts",
        emptyTitle = "아직 완료 기록이 없습니다",
        emptyBody = "먼저 오늘의 루트를 시작해 보세요. 이후 이곳에 평범하지만 빛났던 순간이 저장됩니다.",
        startFirst = "첫 루트 시작",
        relationshipLabel = "관계",
        routeLabel = "루트",
        stopCheckInLabel = "장소 체크인",
        pointsLabel = "포인트",
        durationLabel = "시간",
        completionLabel = "완료",
        hiddenTaskLabel = "숨은 미션",
        keywordsLabel = "키워드",
        openHint = "열어서 이 퀘스트 다시 보기",
        openAction = "열기",
        replayAction = "비슷하게 다시",
    )
    TodayPlayLocale.Spanish -> HistoryStrings(
        title = "Historial",
        subtitle = "library",
        sectionTitle = "Días ya jugados",
        sectionEnglish = "played scripts",
        emptyTitle = "Aún no hay registros completados",
        emptyBody = "Empieza una ruta primero. Luego esta página guardará esos momentos normales que se volvieron especiales.",
        startFirst = "Iniciar primera ruta",
        relationshipLabel = "Relación",
        routeLabel = "Ruta",
        stopCheckInLabel = "Check-ins",
        pointsLabel = "Puntos",
        durationLabel = "Duración",
        completionLabel = "Completado",
        hiddenTaskLabel = "Tarea oculta",
        keywordsLabel = "Palabras clave",
        openHint = "Abrir para revivir esta ruta",
        openAction = "Abrir",
        replayAction = "Repetir estilo",
    )
}
