package com.todayplay.app.localization

data class PrivacyStrings(
    val navLabel: String,
    val title: String,
    val subtitle: String,
    val languageTitle: String,
    val languageBody: String,
    val localDataTitle: String,
    val localDataBody: String,
    val safetyTitle: String,
    val safetyItems: List<String>,
    val historyCount: (Int) -> String,
    val supportTitle: String,
    val supportEmailLabel: String,
    val privacyPolicyLabel: String,
    val contactSupport: String,
    val openPrivacyPolicy: String,
    val notConfigured: String,
    val clearLocalHistory: String,
    val clearDone: String,
    val backHome: String,
)

fun privacyStrings(locale: TodayPlayLocale): PrivacyStrings = when (locale) {
    TodayPlayLocale.SimplifiedChinese -> PrivacyStrings(
        navLabel = "设置",
        title = "隐私与本地数据",
        subtitle = "settings & privacy",
        languageTitle = "语言",
        languageBody = "语言属于个人设置，不打断首页推荐和路线生成。",
        localDataTitle = "本地保存内容",
        localDataBody = "路线副本、打卡状态、反馈原因和积分记录只保存在这台设备上，用于历史回看和通关卡展示。",
        safetyTitle = "当前版本的安全边界",
        safetyItems = listOf(
            "不请求定位、相机、麦克风或通讯录权限。",
            "不上传照片、笔记、对话或路线偏好到服务器。",
            "不抓取第三方平台内容，不在客户端保存 API Key。",
            "购买功能必须等待 Google Play 商品和服务端验单完成后才可正式发放权益。",
        ),
        historyCount = { count -> "当前本地历史：$count 条" },
        supportTitle = "支持与公开政策",
        supportEmailLabel = "支持邮箱",
        privacyPolicyLabel = "隐私政策 URL",
        contactSupport = "联系支持",
        openPrivacyPolicy = "打开隐私政策",
        notConfigured = "正式上架前配置",
        clearLocalHistory = "清空本地历史",
        clearDone = "本地历史已清空",
        backHome = "返回首页",
    )
    TodayPlayLocale.TraditionalChinese -> PrivacyStrings(
        navLabel = "設定",
        title = "隱私與本機資料",
        subtitle = "settings & privacy",
        languageTitle = "語言",
        languageBody = "語言屬於個人設定，不打斷首頁推薦和路線生成。",
        localDataTitle = "本機保存內容",
        localDataBody = "路線副本、打卡狀態、回饋原因和積分記錄只保存在這台裝置上，用於歷史回看和通關卡展示。",
        safetyTitle = "目前版本的安全邊界",
        safetyItems = listOf(
            "不要求定位、相機、麥克風或通訊錄權限。",
            "不上傳照片、筆記、對話或路線偏好到伺服器。",
            "不抓取第三方平台內容，不在客戶端保存 API Key。",
            "購買功能必須等待 Google Play 商品和服務端驗單完成後才可正式發放權益。",
        ),
        historyCount = { count -> "目前本機歷史：$count 筆" },
        supportTitle = "支援與公開政策",
        supportEmailLabel = "支援信箱",
        privacyPolicyLabel = "隱私政策 URL",
        contactSupport = "聯絡支援",
        openPrivacyPolicy = "打開隱私政策",
        notConfigured = "正式上架前配置",
        clearLocalHistory = "清除本機歷史",
        clearDone = "本機歷史已清除",
        backHome = "返回首頁",
    )
    TodayPlayLocale.English -> PrivacyStrings(
        navLabel = "Settings",
        title = "Settings & Privacy",
        subtitle = "settings & privacy",
        languageTitle = "Language",
        languageBody = "Language belongs in settings, so the home screen can stay focused on recommendations and routes.",
        localDataTitle = "Data saved on this device",
        localDataBody = "Itinerary quests, check-in status, feedback reasons, and reward points are stored only on this device for history and completion cards.",
        safetyTitle = "Current safety boundaries",
        safetyItems = listOf(
            "No location, camera, microphone, or contacts permission is requested.",
            "Photos, notes, conversations, and route preferences are not uploaded to a server.",
            "No third-party platform scraping and no API keys are stored in the client.",
            "Paid benefits require Google Play products and server-side purchase verification before real entitlement delivery.",
        ),
        historyCount = { count -> "Local history: $count records" },
        supportTitle = "Support & Public Policy",
        supportEmailLabel = "Support email",
        privacyPolicyLabel = "Privacy policy URL",
        contactSupport = "Contact support",
        openPrivacyPolicy = "Open privacy policy",
        notConfigured = "Configure before launch",
        clearLocalHistory = "Clear local history",
        clearDone = "Local history cleared",
        backHome = "Back home",
    )
    TodayPlayLocale.Japanese -> PrivacyStrings(
        navLabel = "設定",
        title = "設定とプライバシー",
        subtitle = "settings & privacy",
        languageTitle = "言語",
        languageBody = "言語は設定にまとめ、ホーム画面はおすすめとルート開始に集中します。",
        localDataTitle = "端末に保存される内容",
        localDataBody = "ルート、チェックイン状態、フィードバック理由、ポイント記録は履歴とクリアカード表示のため、この端末内にのみ保存されます。",
        safetyTitle = "現在の安全境界",
        safetyItems = listOf(
            "位置情報、カメラ、マイク、連絡先の権限は要求しません。",
            "写真、メモ、会話、ルートの好みはサーバーへアップロードしません。",
            "第三者プラットフォームのスクレイピングは行わず、API Key をクライアントに保存しません。",
            "有料特典は Google Play 商品設定とサーバー側購入検証が完了してから正式に付与します。",
        ),
        historyCount = { count -> "端末内履歴：$count 件" },
        supportTitle = "サポートと公開ポリシー",
        supportEmailLabel = "サポートメール",
        privacyPolicyLabel = "プライバシーポリシー URL",
        contactSupport = "サポートに連絡",
        openPrivacyPolicy = "ポリシーを開く",
        notConfigured = "公開前に設定",
        clearLocalHistory = "端末内履歴を削除",
        clearDone = "端末内履歴を削除しました",
        backHome = "ホームへ戻る",
    )
    TodayPlayLocale.Korean -> PrivacyStrings(
        navLabel = "설정",
        title = "설정 및 개인정보",
        subtitle = "settings & privacy",
        languageTitle = "언어",
        languageBody = "언어는 설정에 두고 홈 화면은 추천과 경로 시작에 집중합니다.",
        localDataTitle = "기기에 저장되는 데이터",
        localDataBody = "루트 퀘스트, 체크인 상태, 피드백 이유, 포인트 기록은 히스토리와 완료 카드 표시를 위해 이 기기에만 저장됩니다.",
        safetyTitle = "현재 버전의 안전 기준",
        safetyItems = listOf(
            "위치, 카메라, 마이크, 연락처 권한을 요청하지 않습니다.",
            "사진, 노트, 대화, 경로 선호도는 서버로 업로드하지 않습니다.",
            "타사 플랫폼을 스크래핑하지 않으며 API Key 를 클라이언트에 저장하지 않습니다.",
            "유료 혜택은 Google Play 상품과 서버 구매 검증이 완료된 뒤 정식으로 지급됩니다.",
        ),
        historyCount = { count -> "로컬 히스토리: ${count}개" },
        supportTitle = "지원 및 공개 정책",
        supportEmailLabel = "지원 이메일",
        privacyPolicyLabel = "개인정보 처리방침 URL",
        contactSupport = "지원팀에 문의",
        openPrivacyPolicy = "개인정보 처리방침 열기",
        notConfigured = "출시 전 설정",
        clearLocalHistory = "로컬 히스토리 삭제",
        clearDone = "로컬 히스토리가 삭제되었습니다",
        backHome = "홈으로 돌아가기",
    )
    TodayPlayLocale.Spanish -> PrivacyStrings(
        navLabel = "Ajustes",
        title = "Ajustes y Privacidad",
        subtitle = "settings & privacy",
        languageTitle = "Idioma",
        languageBody = "El idioma va en ajustes para que el inicio se centre en recomendaciones y rutas.",
        localDataTitle = "Datos guardados en este dispositivo",
        localDataBody = "Las rutas, estados de check-in, motivos de feedback y puntos se guardan solo en este dispositivo para el historial y las tarjetas de finalización.",
        safetyTitle = "Límites de seguridad actuales",
        safetyItems = listOf(
            "No se solicitan permisos de ubicación, cámara, micrófono ni contactos.",
            "Fotos, notas, conversaciones y preferencias de ruta no se suben a un servidor.",
            "No hay scraping de plataformas externas ni API Keys guardadas en el cliente.",
            "Los beneficios de pago requieren productos de Google Play y verificación del servidor antes de entregar derechos reales.",
        ),
        historyCount = { count -> "Historial local: $count registros" },
        supportTitle = "Soporte y política pública",
        supportEmailLabel = "Email de soporte",
        privacyPolicyLabel = "URL de privacidad",
        contactSupport = "Contactar soporte",
        openPrivacyPolicy = "Abrir privacidad",
        notConfigured = "Configurar antes del lanzamiento",
        clearLocalHistory = "Borrar historial local",
        clearDone = "Historial local borrado",
        backHome = "Volver al inicio",
    )
}
