package com.todayplay.app.localization

data class SystemStrings(
    val currentPageCannotPurchase: String,
    val mapOpenedInBrowser: String,
    val mapUnavailableCopiedAddress: String,
    val destinationAddressLabel: String,
    val missingPrefix: String,
    val missingSuffix: String,
    val missingRelationship: String,
    val missingCity: String,
    val missingTime: String,
    val missingBudget: String,
    val missingTransport: String,
    val missingInterests: String,
    val billingNotReadyPrefix: String,
    val billingDisconnected: String,
    val paymentNotOpen: String,
    val productMissingPrefix: String,
    val productMissingSuffix: String,
    val purchaseReturnedNoOrder: String,
    val purchaseCanceled: String,
    val purchaseFailedPrefix: String,
    val verificationSubmitted: String,
    val entitlementFallback: String,
    val verifiedPrefix: String,
    val requiresBackendProductPrefix: String,
    val verificationFailedPrefix: String,
    val queryCompletePrefix: String,
    val queryFailedPrefix: String,
    val cannotOpenPurchasePrefix: String,
) {
    fun missingRequired(field: String): String = "$missingPrefix$field$missingSuffix"
}

fun systemStrings(locale: TodayPlayLocale): SystemStrings = when (locale) {
    TodayPlayLocale.SimplifiedChinese -> zhCnSystem
    TodayPlayLocale.TraditionalChinese -> zhTwSystem
    TodayPlayLocale.English -> enSystem
    TodayPlayLocale.Japanese -> jaSystem
    TodayPlayLocale.Korean -> koSystem
    TodayPlayLocale.Spanish -> esSystem
}

private val zhCnSystem = SystemStrings(
    currentPageCannotPurchase = "当前页面不能启动购买流程。",
    mapOpenedInBrowser = "未安装高德地图，已用浏览器地图打开",
    mapUnavailableCopiedAddress = "未找到可用地图，已复制目的地地址",
    destinationAddressLabel = "目的地地址",
    missingPrefix = "还差一步：请选择",
    missingSuffix = "。",
    missingRelationship = "和谁一起",
    missingCity = "城市",
    missingTime = "时间",
    missingBudget = "预算",
    missingTransport = "交通方式",
    missingInterests = "想做什么",
    billingNotReadyPrefix = "Google Play Billing 未就绪：",
    billingDisconnected = "Google Play Billing 已断开；下一次请求会自动重连。",
    paymentNotOpen = "正式付费暂未开放：Google Play 验单接口还没有配置。你仍然可以免费生成路线副本。",
    productMissingPrefix = "还没有从 Google Play 取到商品：",
    productMissingSuffix = "。需要先在 Play Console 配置商品并通过 Play 分发测试。",
    purchaseReturnedNoOrder = "购买流程已返回，但没有订单数据。",
    purchaseCanceled = "用户取消了购买。",
    purchaseFailedPrefix = "购买失败：",
    verificationSubmitted = "订单已提交验单，等待后端确认后再发放权益。",
    entitlementFallback = "后端未返回权益 key",
    verifiedPrefix = "订单已通过后端验单，可发放权益：",
    requiresBackendProductPrefix = " 商品：",
    verificationFailedPrefix = "订单验单失败：",
    queryCompletePrefix = "Google Play 商品查询完成：",
    queryFailedPrefix = "Google Play 商品查询失败：",
    cannotOpenPurchasePrefix = "无法打开 Google Play 购买页：",
)

private val zhTwSystem = zhCnSystem.copy(
    currentPageCannotPurchase = "目前頁面不能啟動購買流程。",
    mapOpenedInBrowser = "未安裝高德地圖，已用瀏覽器地圖開啟",
    mapUnavailableCopiedAddress = "未找到可用地圖，已複製目的地地址",
    destinationAddressLabel = "目的地地址",
    missingPrefix = "還差一步：請選擇",
    missingSuffix = "。",
    missingRelationship = "和誰一起",
    missingCity = "城市",
    missingTime = "時間",
    missingBudget = "預算",
    missingTransport = "交通方式",
    missingInterests = "想做什麼",
    billingNotReadyPrefix = "Google Play Billing 尚未就緒：",
    billingDisconnected = "Google Play Billing 已斷開；下一次請求會自動重連。",
    paymentNotOpen = "正式付費暫未開放：Google Play 驗單介面還沒有配置。你仍然可以免費生成路線副本。",
    productMissingPrefix = "還沒有從 Google Play 取得商品：",
    productMissingSuffix = "。需要先在 Play Console 配置商品並透過 Play 分發測試。",
    purchaseReturnedNoOrder = "購買流程已返回，但沒有訂單資料。",
    purchaseCanceled = "使用者取消了購買。",
    purchaseFailedPrefix = "購買失敗：",
    verificationSubmitted = "訂單已提交驗單，等待後端確認後再發放權益。",
    entitlementFallback = "後端未返回權益 key",
    verifiedPrefix = "訂單已通過後端驗單，可發放權益：",
    requiresBackendProductPrefix = " 商品：",
    verificationFailedPrefix = "訂單驗單失敗：",
    queryCompletePrefix = "Google Play 商品查詢完成：",
    queryFailedPrefix = "Google Play 商品查詢失敗：",
    cannotOpenPurchasePrefix = "無法開啟 Google Play 購買頁：",
)

private val enSystem = SystemStrings(
    currentPageCannotPurchase = "Purchases cannot start from this screen.",
    mapOpenedInBrowser = "Amap is not installed. Opened the destination in a browser map.",
    mapUnavailableCopiedAddress = "No map app was available. Destination address copied.",
    destinationAddressLabel = "Destination address",
    missingPrefix = "One more step: choose ",
    missingSuffix = ".",
    missingRelationship = "who is going",
    missingCity = "a city",
    missingTime = "a time window",
    missingBudget = "a budget",
    missingTransport = "transport",
    missingInterests = "what you want to do",
    billingNotReadyPrefix = "Google Play Billing is not ready: ",
    billingDisconnected = "Google Play Billing disconnected; the next request will reconnect automatically.",
    paymentNotOpen = "Paid features are not open yet: the Google Play verification endpoint is not configured. You can still generate free route quests.",
    productMissingPrefix = "Google Play has not returned this product yet: ",
    productMissingSuffix = ". Configure it in Play Console and test through Play distribution first.",
    purchaseReturnedNoOrder = "The purchase flow returned without order data.",
    purchaseCanceled = "Purchase canceled.",
    purchaseFailedPrefix = "Purchase failed: ",
    verificationSubmitted = "Order submitted for verification. Benefits will be granted only after backend confirmation.",
    entitlementFallback = "backend returned no entitlement key",
    verifiedPrefix = "Order verified by backend. Entitlements can be granted: ",
    requiresBackendProductPrefix = " Product: ",
    verificationFailedPrefix = "Order verification failed: ",
    queryCompletePrefix = "Google Play product query complete: ",
    queryFailedPrefix = "Google Play product query failed: ",
    cannotOpenPurchasePrefix = "Could not open Google Play purchase page: ",
)

private val jaSystem = enSystem.copy(
    currentPageCannotPurchase = "この画面から購入を開始できません。",
    mapOpenedInBrowser = "高德地図がインストールされていないため、ブラウザの地図で開きました。",
    mapUnavailableCopiedAddress = "利用できる地図アプリがありません。目的地の住所をコピーしました。",
    destinationAddressLabel = "目的地住所",
    missingPrefix = "あと一歩：",
    missingSuffix = "を選んでください。",
    missingRelationship = "誰と行くか",
    missingCity = "都市",
    missingTime = "時間",
    missingBudget = "予算",
    missingTransport = "交通手段",
    missingInterests = "やりたいこと",
    billingNotReadyPrefix = "Google Play Billing の準備ができていません：",
    billingDisconnected = "Google Play Billing が切断されました。次回のリクエストで自動再接続します。",
    paymentNotOpen = "有料機能はまだ開放されていません。Google Play の検証エンドポイントが未設定です。無料ルートは引き続き作成できます。",
    productMissingPrefix = "Google Play から商品を取得できていません：",
    productMissingSuffix = "。先に Play Console で商品を設定し、Play 配信テストを行ってください。",
    purchaseReturnedNoOrder = "購入フローは戻りましたが、注文データがありません。",
    purchaseCanceled = "購入がキャンセルされました。",
    purchaseFailedPrefix = "購入に失敗しました：",
    verificationSubmitted = "注文を検証に送信しました。バックエンド確認後に特典を付与します。",
    entitlementFallback = "バックエンドから特典 key が返されていません",
    verifiedPrefix = "バックエンドで注文確認済み。付与可能な特典：",
    requiresBackendProductPrefix = " 商品：",
    verificationFailedPrefix = "注文検証に失敗しました：",
    queryCompletePrefix = "Google Play 商品照会完了：",
    queryFailedPrefix = "Google Play 商品照会失敗：",
    cannotOpenPurchasePrefix = "Google Play 購入ページを開けません：",
)

private val koSystem = enSystem.copy(
    currentPageCannotPurchase = "이 화면에서는 구매를 시작할 수 없습니다.",
    mapOpenedInBrowser = "고덕지도가 설치되어 있지 않아 브라우저 지도로 열었습니다.",
    mapUnavailableCopiedAddress = "사용 가능한 지도 앱이 없습니다. 목적지 주소를 복사했습니다.",
    destinationAddressLabel = "목적지 주소",
    missingPrefix = "한 단계 남았어요: ",
    missingSuffix = "을(를) 선택해 주세요.",
    missingRelationship = "누구와 갈지",
    missingCity = "도시",
    missingTime = "시간",
    missingBudget = "예산",
    missingTransport = "이동 방식",
    missingInterests = "하고 싶은 것",
    billingNotReadyPrefix = "Google Play Billing 준비 안 됨: ",
    billingDisconnected = "Google Play Billing 연결이 끊겼습니다. 다음 요청에서 자동으로 다시 연결됩니다.",
    paymentNotOpen = "유료 기능은 아직 열리지 않았습니다. Google Play 검증 엔드포인트가 설정되지 않았습니다. 무료 루트는 계속 생성할 수 있습니다.",
    productMissingPrefix = "Google Play에서 아직 상품을 가져오지 못했습니다: ",
    productMissingSuffix = ". 먼저 Play Console에서 상품을 설정하고 Play 배포 테스트를 진행하세요.",
    purchaseReturnedNoOrder = "구매 흐름이 돌아왔지만 주문 데이터가 없습니다.",
    purchaseCanceled = "구매가 취소되었습니다.",
    purchaseFailedPrefix = "구매 실패: ",
    verificationSubmitted = "주문을 검증에 제출했습니다. 백엔드 확인 후 혜택이 지급됩니다.",
    entitlementFallback = "백엔드가 혜택 key를 반환하지 않았습니다",
    verifiedPrefix = "백엔드에서 주문이 검증되었습니다. 지급 가능한 혜택: ",
    requiresBackendProductPrefix = " 상품: ",
    verificationFailedPrefix = "주문 검증 실패: ",
    queryCompletePrefix = "Google Play 상품 조회 완료: ",
    queryFailedPrefix = "Google Play 상품 조회 실패: ",
    cannotOpenPurchasePrefix = "Google Play 구매 페이지를 열 수 없습니다: ",
)

private val esSystem = enSystem.copy(
    currentPageCannotPurchase = "No se puede iniciar una compra desde esta pantalla.",
    mapOpenedInBrowser = "Amap no está instalado. Se abrió el destino en un mapa del navegador.",
    mapUnavailableCopiedAddress = "No hay una app de mapas disponible. Dirección copiada.",
    destinationAddressLabel = "Dirección de destino",
    missingPrefix = "Un paso más: elige ",
    missingSuffix = ".",
    missingRelationship = "con quién vas",
    missingCity = "una ciudad",
    missingTime = "un horario",
    missingBudget = "un presupuesto",
    missingTransport = "transporte",
    missingInterests = "qué quieres hacer",
    billingNotReadyPrefix = "Google Play Billing no está listo: ",
    billingDisconnected = "Google Play Billing se desconectó; la próxima solicitud reconectará automáticamente.",
    paymentNotOpen = "Los pagos aún no están abiertos: falta configurar el endpoint de verificación de Google Play. Todavía puedes generar rutas gratis.",
    productMissingPrefix = "Google Play aún no devolvió este producto: ",
    productMissingSuffix = ". Configúralo primero en Play Console y pruébalo mediante distribución de Play.",
    purchaseReturnedNoOrder = "El flujo de compra volvió sin datos de pedido.",
    purchaseCanceled = "Compra cancelada.",
    purchaseFailedPrefix = "Error de compra: ",
    verificationSubmitted = "Pedido enviado a verificación. Los beneficios se otorgarán solo tras confirmación del backend.",
    entitlementFallback = "el backend no devolvió clave de beneficio",
    verifiedPrefix = "Pedido verificado por backend. Beneficios disponibles: ",
    requiresBackendProductPrefix = " Producto: ",
    verificationFailedPrefix = "Error al verificar el pedido: ",
    queryCompletePrefix = "Consulta de productos de Google Play completa: ",
    queryFailedPrefix = "Error en consulta de productos de Google Play: ",
    cannotOpenPurchasePrefix = "No se pudo abrir la página de compra de Google Play: ",
)
